// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tamagotchi.Competition.Context;

namespace Tamagotchi.Competition.Migrations
{
    [DbContext(typeof(TamagotchiCompetitionContext))]
    [Migration("20190120201712_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Tamagotchi.Competition.Context.Events", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasColumnName("ACTION_CODE")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("DeseaseCode")
                        .HasColumnName("DESEASE_CODE")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<TimeSpan>("Finish")
                        .HasColumnName("FINISH")
                        .HasColumnType("time");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnName("ROOM_CODE")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<TimeSpan>("Start")
                        .HasColumnName("START")
                        .HasColumnType("time");

                    b.Property<int>("Value")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.ToTable("EVENTS");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActionCode = "brush",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "playRoom",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 5
                        },
                        new
                        {
                            Id = 2L,
                            ActionCode = "takePicture",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "playRoom",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 10
                        },
                        new
                        {
                            Id = 3L,
                            ActionCode = "playBall",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "playRoom",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 15
                        },
                        new
                        {
                            Id = 4L,
                            ActionCode = "playTicTacToe",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "playRoom",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 15
                        },
                        new
                        {
                            Id = 5L,
                            ActionCode = "giveAntiviral",
                            DeseaseCode = "cold",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "hospital",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 100
                        },
                        new
                        {
                            Id = 6L,
                            ActionCode = "pshikIngalipt",
                            DeseaseCode = "angina",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "hospital",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 100
                        },
                        new
                        {
                            Id = 7L,
                            ActionCode = "stripCandy",
                            DeseaseCode = "inflammationTricks",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "hospital",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 100
                        },
                        new
                        {
                            Id = 8L,
                            ActionCode = "giveAntihistamine",
                            DeseaseCode = "allergy",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "hospital",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 100
                        },
                        new
                        {
                            Id = 9L,
                            ActionCode = "dumplings",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "kitchen",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 50
                        },
                        new
                        {
                            Id = 10L,
                            ActionCode = "pizza",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "kitchen",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 45
                        },
                        new
                        {
                            Id = 11L,
                            ActionCode = "paste",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "kitchen",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 30
                        },
                        new
                        {
                            Id = 12L,
                            ActionCode = "soup",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "kitchen",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 25
                        },
                        new
                        {
                            Id = 13L,
                            ActionCode = "porridge",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "kitchen",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 20
                        },
                        new
                        {
                            Id = 14L,
                            ActionCode = "yogurt",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "kitchen",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 15
                        },
                        new
                        {
                            Id = 15L,
                            ActionCode = "oatCookies",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "kitchen",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 2
                        },
                        new
                        {
                            Id = 16L,
                            ActionCode = "apple",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "kitchen",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 5
                        },
                        new
                        {
                            Id = 17L,
                            ActionCode = "water",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "kitchen",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 3
                        },
                        new
                        {
                            Id = 18L,
                            ActionCode = "tea",
                            Finish = new TimeSpan(0, 23, 0, 0, 0),
                            RoomCode = "kitchen",
                            Start = new TimeSpan(0, 0, 0, 0, 0),
                            Value = 3
                        });
                });

            modelBuilder.Entity("Tamagotchi.Competition.Context.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<long>("UserId")
                        .HasColumnName("USER_ID");

                    b.Property<int>("Value")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.ToTable("SCORE");
                });
#pragma warning restore 612, 618
        }
    }
}
