// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tamagotchi.Competition.Context;

namespace Tamagotchi.Competition.Migrations
{
    [DbContext(typeof(TamagotchiCompetitionContext))]
    partial class TamagotchiCompetitionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Tamagotchi.Competition.Context.Events", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasColumnName("ACTION_CODE")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("DeseaseCode")
                        .HasColumnName("DESEASE_CODE")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<DateTime>("Finish")
                        .HasColumnName("FINISH")
                        .HasColumnType("date");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnName("ROOM_CODE")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<DateTime>("Start")
                        .HasColumnName("START")
                        .HasColumnType("date");

                    b.Property<int>("Value")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.ToTable("EVENTS");
                });

            modelBuilder.Entity("Tamagotchi.Competition.Context.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<long>("UserId")
                        .HasColumnName("USER_ID");

                    b.Property<int>("Value")
                        .HasColumnName("VALUE");

                    b.HasKey("Id");

                    b.ToTable("SCORE");
                });
#pragma warning restore 612, 618
        }
    }
}
